### ISSUE TITLE
Http/Https Intercept: https edge case problems

### ISSUE THREAD

**Issue by robblovell** [c6o/roadmap#1]
### Summary:
Investigating a case where intercepting an edge service with an https ingress failed to intercept failed to forward https.

### To Reproduce:
TBD

### Observed Results:
TBD

### Expected Behaviour:
https traffic is forwarded

## Checklist
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I have provided sufficient information for the team

**Comment by nsainaney** [comment]
We tested this at our end and are not able to reproduce the issue. We are using the GKE ingress provider and HTTPS traffic terminates at the LB and upstream traffic is HTTP.

Our interceptor captures all traffic (HTTP/HTTPS) and forwards it upstream to an HTTP tunnel on your local machine or to the HTTP service in-cluster.

**Comment by nsainaney** [comment]
We've done some further checking and it appears that some proxy servers convert the 301/302 from our proxy to a 303 and force the scheme to HTTPS even if the internal service scheme was HTTP. The solution would be to spawn both a HTTP and HTTPS local tunnel.
