### ISSUE TITLE
Teleport does not ask for a namespace if one is not given.

### ISSUE THREAD

**Issue by robblovell** [c6o/roadmap#13]
### Summary:
When using teleport, as of version 0.3.2, if you leave off a namespace it does not ask you for which one you want to use.

### To Reproduce:
Steps to reproduce the behaviour:
1. Install halyard demo into the default namespace.
2. Using the documentation's example commands with the halyard demo: `czctl deployment teleport halyard-echo`

### Observed Results:
It does not ask for a namespace and does not use default and does not find the resource.

### Expected Behaviour:
It should ask for a namespace.

**Comment by nsainaney** [comment]
Fixed in 1.3.2 onward
