### ISSUE TITLE
Opt-out of usage analytics

### ISSUE THREAD

**Issue by conneryn** [c6o/roadmap#22]
### Business Requirements:
Currently we collect basic anonymized usage analytics (using Google Analytics) to help us to understand how users are using CodeZero, find sources of friction, and help us prioritize engineering focus.   However, we should provide users with the ability to opt-out of this collection.

### Technical Requirements:
* MUST allow user to completely disable all google analytics tracking data from being sent (should not even connect to GA servers)
* MUST be able to opt-out at any time  (ex: via single command)
* Should be able to opt back in
* Could be opt-in instead

### UX/UI Design
Both CLI and GUI should provide ability to change analytics preferences.

Potential CLI command:
`czctl config usage-analytics disabled`

### Architetural Drawings
Work in Progress.

**Comment by nsainaney** [comment]
I understand that start will be replacing init in the next release. How would one trigger this after start? Would the following work?

```
czctl start

.... do stuff

czctl start --no-unsage-tracking
```

or

```
czctl start
czctl stop
czctl start --no-unsage-tracking
```

or

```
czctl start
czctl config no-usage-tracking
```
