### ISSUE TITLE
kuma support

### ISSUE THREAD

**Issue by mayaaravotwm** [c6o/roadmap#30]
hello, 
we have kong ingress as our ingress controller on our aws eks cluster, and kuma as our service mesh.
whenever we intercept or teleport a deployment, we can't access the service from outside, only from the inside. so the internal routes work well but the external don't work. it is relevant to both the original service and the intercepted one as well.
we have kuma sidecar added to each pod in the namespace, your intercepted pod gets it as well.

what can we do?

@c6o/cli/1.1.1 darwin-x64 node-v14.17.3

**Comment by conneryn** [comment]
Hi Maya,

We know that CodeZero needs to play well with services mesh controllers and gracefully navigate control of services. This is a work in progress.  We have more experience with service meshes like istio however, and we haven't had a chance to play with Kuma yet. 

We very much appreciate you bringing Kuma to our attention.  One of our engineers will be look into getting a cluster up and configured with Kuma to perform some testing, and we will report back as we know more, but this may take some time to setup and diagnose.

If you can spare a moment, I'd love to jump on a chat with you about your current setup to better understand what and how you are using Kuma.  This would really help speed up this process and ensure we actually consider the right situation(s).  If that is something you'd be open to, please reach out to me at connery@codezero.io and we can set up a time!

Many thanks,
Connery

**Comment by conneryn** [comment]
Quick update to this issue:  Intercept appears to play nicely with a vanilla Kuma setup (including with Mutual TLS enabled).   However, more advanced configurations could very likely still cause complications  (for example, we anticipated that strict `TrafficRoutes` or `TrafficPermissions` may result in conflicts with intercept).

We will continue to diagnose the cause of this issue, and will update this ticket as we learn more.

**Comment by conneryn** [comment]
After digging deeper into this issue, we found the root cause of the original issue did not actually have to do with any incompatibility between Kuma/Kong and CodeZero. Instead, we identified a bug in how CodeZero handles named ports (See https://github.com/c6o/roadmap/issues/32 for full details).
