### ISSUE TITLE
czctl for Windows

### ISSUE THREAD

**Issue by fox-md** [c6o/roadmap#33]
### Question

I am trying to run `czctl start` on windows 10 machine

```
VERSION
  @c6o/cli/1.2.4 win32-x64 node-v14.15.0
```

and getting below error

```
C:\WINDOWS\system32>czctl start

process.geteuid is not a function
```

Can you please advise, does it suppose to work on windows?

**Comment by nsainaney** [comment]
Hi @fox-md,
The cli requires MacOS/Linux or the Windows Subsystem for Linux at this time.

Windows support is in the works.

Well make sure we have a better error message in the next release.

**Comment by nsainaney** [comment]
@conneryn 

Here's how we can check for OS: https://stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js

**Comment by fox-md** [comment]
Hi @nsainaney,
Thank you the prompt reply. Will try to run using Windows Subsystem for Linux.
