### ISSUE TITLE
Slow installation of `czctl`

### ISSUE THREAD

**Issue by conneryn** [c6o/roadmap#42]
### Summary:

Installing `czctl` takes a long time.  Whether via `npm` or `brew`.  The `brew` experience is even worse because it does not provide feedback that anything is happening, so appears to have hung.

This is due to the number of NPM dependencies that need to be checked and installed whenever installing the CLI.

Improving the brew experience could be accomplished via: https://github.com/c6o/roadmap/issues/43

### To Reproduce:

1. `brew install c6o/tools/czctl` or `npm install -g @c6o/cli`

### Observed Results:
Takes a long time.

**Comment by nsainaney** [comment]
We fixed this in v1.4.0
