### ISSUE TITLE
Automatically create `bottles` for `brew` Formulae

### ISSUE THREAD

**Issue by conneryn** [c6o/roadmap#43]
### New Change, Reorganization, System or Architecture.

Brew can reference pre-built binaries of a package (called `bottles`).  To improve the experience of installing the CLI via brew, and avoid complications with users node version, we create and publish bottles for each of the major operating systems/architectures.

### Expected Benefit 

1. Faster installation experience.
1. Remove depence on users local version of node.

### Systems to be changed

Publishing processes of brew formulae for `czctl`

**Comment by nsainaney** [comment]
We've switched to using a simple shell script for installs so brew bottles may not be needed. Closing for now
