### ISSUE TITLE
Support for ExternalName type Services

### ISSUE THREAD

**Issue by lukedoesinfra** [c6o/roadmap#49]
Addition of support specifically for services that use ExternalName types. 

### Expected Benefit 

Engineers able to access development RDS databases via `czctl teleport namespace <namespace>`

### Current behaviour

Currently it looks as if the IP address for that specific service doesn't get created and put into the /etc/hosts file.

```
❯ kubectl get svc -n <namespace>
NAME                      TYPE           CLUSTER-IP       EXTERNAL-IP                                                      PORT(S)    AGE
svc1                   ClusterIP      172.20.220.173   <none>                                                           8125/UDP   15d
database   ExternalName   <none>           <DBURL>  <none>     18h
svc2                    ClusterIP      172.20.230.40    <none>                                                           3000/TCP   24d
```

```
127.1.27.1       <snip all svc1 DNS> 
127.1.27.2      <snip all svc2 DNS>
```

**Comment by conneryn** [comment]
Thanks for reporting the issue! We are looking into supporting this and we will update here as we iron out the details.

Quick clarification about your particular situation:
Would traffic to `<DBURL>` need to come from within the cluster, or could your local machine talk directly to the database?  For example, I think RDS is usually (always?) only accessible from within AWS and/or specific VPCs (though, my RDS experience is definitely rusty).

**Comment by nsainaney** [comment]
@lukedoesinfra, thanks for reporting. @conneryn, ExternalName can point to an outside resource or within the cluster. We may want to see if the ExternalName matches `<svc>.<namespace>` or `<svc>.<namespace>.svc.cluster.local` would check to see that that additional service is also teleported. Should be straightforward as we can do a quick lookup to determine internal vs external.

**Comment by nsainaney** [comment]
@conneryn, in the interest of time, we can simply issue a warning if the other service is not also teleported if ExternalName is in-cluster.

**Comment by conneryn** [comment]
I'm not sure if it's necessary to have a distinction between in-cluster and external destinations for `ExternalName` services (at least, not to start). If we solve the problem for proxy/routing traffic through the cluster to external destinations, that solution would also work for any in-cluster destinations. Albeit, avoiding the need for a proxy for in-cluster destination could be a potential optimization, I don't think it's functionally required.

As for a solution.  We already have the notion of a "podless" service, where CodeZero creates a proxy in the cluster to route traffic on-behalf of services that don't have an explicit in-cluster pod.  This is essentially what an `ExternalName` service is, but we just don't currently treat them as a "podless" service, yet. This should be a relatively simple addition.  We will do a bit more validation on this as a solution but will update here once we have finalized the approach.

**Comment by lukedoesinfra** [comment]
> Would traffic to <DBURL> need to come from within the cluster, or could your local machine talk directly to the database? For example, I think RDS is usually (always?) only accessible from within AWS and/or specific VPCs (though, my RDS experience is definitely rusty).

In our situation, the databases are only accessible via the EKS Cluster via security groups. The client will not be able to speak directly to the database.

However, RDS instances can be made public and protected with security groups, locking the cluster down with IPs for example.

 I think the `podless` service is what i'm expecting as behaviour for `ExternalName` services.

**Comment by conneryn** [comment]
Yes, thanks @lukedoesinfra, that all makes perfect sense!  And thanks for the details on how other users could have configured their RDS protection.  

We have come up with an initial implementation to resolve this issue.  We still need to do some more extensive testing, but we have pushed out the change in our latest canary build (version `1.8.0-canary.1`). Unless anything totally unexpected comes up, we should be able to publish this in our next stable build by mid-next week.

**Comment by lukedoesinfra** [comment]
@conneryn - Thank so for doing this so quick! Real game changer for us!

**Comment by conneryn** [comment]
@lukedoesinfra version 1.8.0 was released yesterday.  Teleporting to `ExternalName` services should now be working! Let me know if you are still experiencing any issues or have any other questions.
