### ISSUE TITLE
Intercept Cannot read properties of undefined (reading 'routes')

### ISSUE THREAD

**Issue by zoop-btc** [c6o/roadmap#51]
### Summary:
Intercept unable to forward service. Version 1.8.1

### To Reproduce:
I run this command to intercept a simple service which serves a node application:
`czctl intercept service frontend -n frontend -r 80 -l 3000 -a`
I am a cluster-admin. Kubernetes Version is v1.25.6+rke2r1. I use Cilium as CNI.

### Observed Results:
I'm getting the error message **Cannot read properties of undefined (reading 'routes')** (image1)
It creates a Session in the Cluster but not a local one. Other than the Session nothing else is created on the cluster. (image2)
Then I switched to the Canary deployment and it seems to work there however instead of the webpage I get NGROK asking me for an authtoken. (image3)
Rollback to an earlier version (1.7.1) and this time it creates the resources in the cluster, however the interceptor pod is in a crash loop with the message "unknown whereschema variable".

### Expected Behavior:
I'd expect intercept to forward the port as intended.

### Screenshots:
![image](https://user-images.githubusercontent.com/101409458/223850087-b6b8cc37-f4a0-47ca-9264-ed5754fa9279.png)
![image](https://user-images.githubusercontent.com/101409458/223850148-85a5365f-e657-4736-8974-6ad2f155c369.png)
![image](https://user-images.githubusercontent.com/101409458/223849382-2dc5ae32-c3f9-454e-a115-9989abc21b85.png)

### Failure Logs
None

## Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)
- [x] I have provided sufficient information for the team

**Comment by nsainaney** [comment]
Hi @zoop-btc, thanks for the detailed report. We have encountered this issue when the intercept is unable to find a matching port on the service/pod. Can you post the service config?

**Comment by zoop-btc** [comment]
Sure, thank you for taking the time @nsainaney . This is the output of `kubectl -n frontend get service frontend -o yaml`
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"frontend","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"frontend","app.kubernetes.io/version":"1.16.0","argocd.argoproj.io/instance":"frontend","helm.sh/chart":"frontend-0.1.0"},"name":"frontend","namespace":"frontend"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"frontend","app.kubernetes.io/name":"frontend"},"type":"ClusterIP"}}
  creationTimestamp: "2023-03-08T20:06:49Z"
  labels:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: frontend
    app.kubernetes.io/version: 1.16.0
    argocd.argoproj.io/instance: frontend
    helm.sh/chart: frontend-0.1.0
  name: frontend
  namespace: frontend
  resourceVersion: "1669096"
  uid: 26c480fc-aaaa-41a4-ae88-bd2ee7cd2535
spec:
  clusterIP: 10.43.220.190
  clusterIPs:
  - 10.43.220.190
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

I won't post the whole deployment but here's the ports on it. It sure works as I can access it through the ingress without issues.
```
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
```

**Comment by zoop-btc** [comment]
@nsainaney I guess the issue was with named ports. I have removed all the names and referenced the ports directly. Then it worked. Intercept does the forwarding as far as I can see.

However now I'm getting the same ngrok error message (ERR_NGROK_6022) about the authtoken.
How can I resolve that?
