### ISSUE TITLE
Cannot create intercept

### ISSUE THREAD

**Issue by rightytighty** [c6o/roadmap#53]
### Summary

I am attempting to create my first service intercept with c6o in a managed k8s cluster, but I am getting failures.

### To Reproduce

1. Installed c6o CLI v1.9.0 on Oracle Linux 7.9.
2. Configured ~/.kube/config to k8s cluster.  kubectl commands work with cluster-admin access.
3. Started c6o daemon: czctl start
4. Attempt to create intercept:

$ czctl intercept service -n default incidents-service
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
(node:1064) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `czctl --trace-deprecation ...` to show where the warning was created)

✖ Initiating intercept                                                                                                                                                                             Failed!
✖  Intercept request received                                                                                                                                                                      Failed!
✖  Validating intercept parameters                                                                                                                                                                 Failed!

404 - {"timestamp":"2023-06-17T20:51:41.649+00:00","status":404,"error":"Not Found","path":"/api/v1"}

### Observed Results

The czctl intercept service call has failure text, and the intercept is not in effect.
Also note that there are not any "Session" CRDs in cluster...?

### Expected Behavior

The intercept is in effect.

### Screenshots

None.

### Failure Logs

I don't know where there are logs for c6o.
Is there a way to get more info about what is failing?

## Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

**Comment by nsainaney** [comment]
Hi @rightytighty - apologies for just now seeing this.

Can you share if you are on ARM or x64 linux? Also, do you have the appropriate permissions on the cluster? A 404 is sometimes a sign of a permission issue (https://docs.codezero.io/#/guides/security)

The binaries for codezero v1 are installed in `/usr/local/bin/codezero`. You should see a `czdaemon` there. You can observe logs by running:

```
sudo czctl stop
export DEBUG=*,-engine*,-nodemon*,-*expo*,-babel*,-winston*,-follow-redirects*
sudo czdaemon
```

The daemon will start spewing logs now (you can do `DEBUG=*` but that'll likely be a little too verbose)

Running `czctl service intercept` in a different terminal will then output logs on the `czdaemon` terminal.
